# macOS Homebrew formulae (install.sh uses this on Darwin only)
brew "asdf"
brew "bat"
brew "cmake"
brew "curl"
brew "gh"
brew "gnupg"
brew "helm"
brew "jq"
brew "k9s"
brew "lua-language-server"
brew "neovim"
brew "openapi-generator"
brew "protobuf"
brew "ripgrep"
brew "ruff"
brew "skaffold"
brew "tree"
brew "tree-sitter-cli"
brew "yq"

tap "anomalyco/tap"
brew "anomalyco/tap/opencode-v2"
